# Tên của quy trình
name: Deploy to Production Server

# Chạy quy trình này khi có code mới được đẩy lên nhánh 'main'
on:
  push:
    branches:
      - main

# Các công việc cần làm
jobs:
  deploy:
    name: Deploy Code to Server
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Cài đặt khóa SSH để kết nối
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      # Bước 2: Thêm IP máy chủ vào danh sách tin cậy
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Bước 3: Đăng nhập vào máy chủ và chạy lệnh triển khai
      - name: Deploying to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "--- Starting deployment on server ---"
            # Di chuyển đến đúng thư mục dự án trên máy chủ
            cd /var/www/Hpt10T9
            
            echo "--- Pulling latest code from GitHub main branch ---"
            git pull origin main
            
            echo "--- Rebuilding and restarting Docker containers ---"
            docker-compose up -d --build
            
            echo "--- Cleaning up old Docker images ---"
            docker image prune -f
            
            echo "--- Deployment successful! ---"
